/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_sf_jniinchi_JniInchiWrapper */

#ifndef _Included_net_sf_jniinchi_JniInchiWrapper
#define _Included_net_sf_jniinchi_JniInchiWrapper
#ifdef __cplusplus
extern "C" {
#endif
#undef net_sf_jniinchi_JniInchiWrapper_MAXVAL
#define net_sf_jniinchi_JniInchiWrapper_MAXVAL 20L
#undef net_sf_jniinchi_JniInchiWrapper_MAX_LOCK_TIMEOUT
#define net_sf_jniinchi_JniInchiWrapper_MAX_LOCK_TIMEOUT 15L
#undef net_sf_jniinchi_JniInchiWrapper_WINDOWS
#define net_sf_jniinchi_JniInchiWrapper_WINDOWS 1L
#undef net_sf_jniinchi_JniInchiWrapper_LINUX
#define net_sf_jniinchi_JniInchiWrapper_LINUX 2L
/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiGenerateInchiFromInchi
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiGenerateInchiFromInchi
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiGetInchi
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiGetInchi
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiGetAuxInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiGetAuxInfo
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiGetMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiGetMessage
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiGetLog
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiGetLog
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiFreeInputMem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiFreeInputMem
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiFreeOutputMem
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiFreeOutputMem
  (JNIEnv *, jobject);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    LibInchiGetVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_sf_jniinchi_JniInchiWrapper_LibInchiGetVersion
  (JNIEnv *, jclass);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    getINCHI
 * Signature: (Lnet/sf/jniinchi/JniInchiInput;)Lnet/sf/jniinchi/JniInchiOutput;
 */
JNIEXPORT jobject JNICALL Java_net_sf_jniinchi_JniInchiWrapper_getINCHI
  (JNIEnv *, jobject, jobject);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    getINCHIKeyFromINCHI
 * Signature: (Ljava/lang/String;)Lnet/sf/jniinchi/JniInchiOutputKey;
 */
JNIEXPORT jobject JNICALL Java_net_sf_jniinchi_JniInchiWrapper_getINCHIKeyFromINCHI
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    CheckINCHIKey
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_net_sf_jniinchi_JniInchiWrapper_CheckINCHIKey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     net_sf_jniinchi_JniInchiWrapper
 * Method:    GetStructFromINCHI
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Lnet/sf/jniinchi/JniInchiOutputStructure;
 */
JNIEXPORT jobject JNICALL Java_net_sf_jniinchi_JniInchiWrapper_GetStructFromINCHI
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
