#
# Makefile for JNI-InChI - Macintosh Settings
#
# Author: Sam Adams <sea36 at users.sourceforge.net>
#         Unilever Centre for Molecular Science Informatics
#         University Of Cambrige, UK
#

LDFLAGS = -dynamiclib -single_module
                                                                                                                                     
CFLAGS += -I"${JAVA_HOME}/include" -I$(JNI_SRCDIR) -I$(INCHI_SRCDIR) -arch i386 -arch x86_64          