#
# Makefile for InChI v1.02-beta - Windows settings
#
# Author: Sam Adams <sea36@cam.ac.uk>
#         Unilever Centre for Molecular Science Informatics
#         University Of Cambrige, UK
#

CXXFLAGS = -I"$(JAVA_HOME)/include/win32"
LDFLAGS += -Wl,--add-stdcall-alias

LIB_PREFIX = lib 
LIB_SUFFIX = .dll
LIB_OS = WINDOWS
