#
# Makefile for JNI-InChI - FreeBSD Settings
#
# Author: Vedrin Jeliazkov <vedrin.jeliazkov at gmail.com>
# Ideaconsult Ltd., BG
#

CFLAGS += -I$(JAVA_HOME)/include/freebsd -fPIC
LDFLAGS += -shared

LIB_PREFIX = lib
LIB_SUFFIX = .so
