#
# Makefile for JNI-InChI - Macintosh Settings
#
# Author: Sam Adams <sea36@cam.ac.uk>
#         Unilever Centre for Molecular Science Informatics
#         University Of Cambrige, UK
#

#CFLAGS = -fPIC
#CXXFLAGS = -fPIC
LDFLAGS = -dynamiclib -single_module

LIB_PREFIX = lib
LIB_SUFFIX = .jnilib
