
# GCC based makefile

LDFLAGS += -s
CFLAGS += -I"${JAVA_HOME}/include" -I$(INCHI_SRCDIR)
CFLAGS += -Os -ansi -pedantic

$(TARGET): $(INCHI_OBJECTS) $(JNI_OBJECTS)
	$(LINK.c) $^ -o $@

$(INCHI_OBJDIR)/%.o: $(INCHI_SRCDIR)/%.c
	$(COMPILE.c) $< -o $@

$(JNI_OBJDIR)/%.o: $(JNI_SRCDIR)/%.c $(JNI_HEADERS)
	$(COMPILE.c) $< -o $@ -I$(JNI_HEADER_DIR)
