#
# Makefile for JNI-InChI - Linux Settings
#
# Author: Sam Adams <sea36@cam.ac.uk>
#         Unilever Centre for Molecular Science Informatics
#         University Of Cambrige, UK
#

CFLAGS = -fPIC
CXXFLAGS = -I$(JAVA_HOME)/include/linux -fPIC

LIB_PREFIX = lib
LIB_SUFFIX = .so
LIB_OS = LINUX
